name: simple_news_app
description: It is an application that gathers all the information from various media 

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.6
  dio: ^5.3.3
  flutter:
    sdk: flutter
  flutter_iconly: ^1.0.2
  google_fonts: ^6.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.18.1
  ionicons: ^0.2.2
  like_button: ^2.0.5
  pull_to_refresh: ^2.0.0
  share_plus: ^8.0.0
  url_launcher: ^6.1.14

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^2.0.3
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  rename: ^3.0.0

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon/icon.png"
  image_path_android: "assets/icon/icon.png"
  adaptive_icon_foreground: "assets/icon/foreground.png"

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/icon/icon.png
    - assets/icon/foreground.png
    
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
